<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="IBM-PG02TZZN" failures="14" tests="30" name="Test" time="7.883" errors="0" timestamp="14 Sep 2023 08:14:32 GMT">
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="2.165">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="2.165">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="2.165">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="2.165">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="2.167">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="2.166">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="2.166">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="2.166">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="2.166">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="2.167">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="0.478">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="0.48">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="0.511">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.DeleteCustomer" name="deleteCustomer" time="0.513">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomer.deleteCustomer(DeleteCustomer.java:19)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="testCases.CreateCustomerStripeAPIbasic" name="cxCreationValidKey" time="0.817"/>
  <testcase classname="testCases.CreateCustomerStripeAPIbasic" name="cxCreationValidKey" time="0.495"/>
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationValidKey" time="0.673"/>
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationValidKey" time="0.682"/>
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationValidKey" time="0.974"/>
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationValidKey" time="1.123"/>
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationValidKey" time="1.132"/>
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationValidKey" time="1.137"/>
  <testcase classname="testCases.CreateCustomerStripeAPIbasic" name="cxCreationInvalidKey" time="0.473"/>
  <testcase classname="testCases.CreateCustomerStripeAPIbasic" name="cxCreationInvalidKey" time="0.465"/>
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationInvalidKey" time="0.288"/>
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationInvalidKey" time="0.303"/>
  <testcase classname="testCases.CreateCustomerStripeAPI2" name="cxCreationInvalidKey" time="0.303"/>
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationInvalidKey" time="0.457"/>
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationInvalidKey" time="0.466"/>
  <testcase classname="testCases.CreateCustomerStripeAPI" name="cxCreationInvalidKey" time="0.476"/>
  <testcase classname="baseClass.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
  <testcase classname="baseClass.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
  <testcase classname="baseClass.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
</testsuite> <!-- Test -->
